// web/src/components/NotificationCenter.vue
<template>
  <div v-if="visible" class="modal-overlay" @click="onClose">
    <div class="modal-content" @click.stop>
      <div class="modal-header">
        <h2 class="modal-title">Notificações</h2>
        <button class="close-button" @click="onClose">×</button>
      </div>
      
      <div class="modal-body">
        <div v-if="loading" class="loading-container">
          <div class="loading-spinner"></div>
          <p class="loading-text">Carregando notificações...</p>
        </div>
        
        <div v-else-if="notifications.length === 0" class="empty-container">
          <div class="empty-icon">✅</div>
          <h3 class="empty-title">Nenhuma notificação</h3>
          <p class="empty-subtitle">Todos os pagamentos estão em dia!</p>
        </div>
        
        <div v-else class="notifications-list">
          <div v-for="(notification, index) in notifications" :key="index" class="notification-card">
            <div class="notification-header">
              <div class="notification-icon" :class="getNotificationIconClass(notification.type, notification.daysUntilDue)">
                {{ getNotificationIcon(notification.type, notification.daysUntilDue) }}
              </div>
              <div class="notification-content">
                <h4 class="notification-title">{{ getNotificationTitle(notification.type, notification.daysUntilDue) }}</h4>
                <p class="customer-name">{{ notification.customerName || 'Cliente não informado' }}</p>
                <p class="product-name">{{ notification.productName }}</p>
                <p class="installment-info">
                  Parcela {{ notification.installment.number }} de {{ notification.totalInstallments }}
                </p>
              </div>
              <div class="notification-values">
                <div class="amount">{{ formatCurrency(notification.installment.value) }}</div>
                <div class="due-date">{{ formatDate(notification.installment.dueDate) }}</div>
              </div>
            </div>
            
            <div class="notification-actions">
              <button class="pay-button" @click="handleMarkAsPaid(notification)">
                <span class="pay-icon">✓</span>
                Marcar como Pago
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue'
import { useAppStore } from '../stores/app'

const store = useAppStore()

interface NotificationItem {
  sale: any
  installment: {
    id: string
    number: number
    value: number
    dueDate: string
    status: string
  }
  customerName?: string
  productName: string
  totalInstallments: number
  daysUntilDue: number
  daysOverdue?: number
  type: 'upcoming' | 'overdue'
}

interface Props {
  visible: boolean
}

const props = defineProps<Props>()
const emit = defineEmits<{
  close: []
}>()

const onClose = () => {
  emit('close')
}

const notifications = ref<NotificationItem[]>([])
const loading = ref(false)

// Load real notifications from sales with installments
const loadNotifications = async () => {
  loading.value = true
  try {
    // Load real sales data to check for pending installments
    await store.fetchSales()
    
    const sales = store.sales || []
    const notificationList: NotificationItem[] = []
    
    // Check each sale for pending installments
    sales.forEach(sale => {
      if (sale.installments && sale.installments.length > 0) {
        sale.installments.forEach(installment => {
          if (installment.status === 'pending' || installment.status === 'overdue') {
            const dueDate = new Date(installment.dueDate)
            const today = new Date()
            const daysUntilDue = Math.ceil((dueDate.getTime() - today.getTime()) / (1000 * 60 * 60 * 24))
            
            notificationList.push({
              sale: sale,
              installment: installment,
              customerName: sale.customerName || 'Cliente',
              productName: sale.product || 'Produto',
              totalInstallments: sale.installments.length,
              daysUntilDue: daysUntilDue,
              type: daysUntilDue <= 0 ? 'overdue' : daysUntilDue <= 3 ? 'urgent' : 'upcoming'
            })
          }
        })
      }
    })
    
    notifications.value = notificationList
  } catch (error) {
    console.error('Error loading notifications:', error)
  } finally {
    loading.value = false
  }
}

const formatCurrency = (value: number) => {
  return new Intl.NumberFormat('pt-BR', {
    style: 'currency',
    currency: 'BRL'
  }).format(value)
}

const formatDate = (dateString: string) => {
  return new Date(dateString).toLocaleDateString('pt-BR', {
    day: '2-digit',
    month: '2-digit',
    year: 'numeric'
  })
}

const getNotificationIcon = (type: 'upcoming' | 'overdue', days: number) => {
  if (type === 'overdue') return '⚠️'
  if (days === 0) return '⏰'
  if (days <= 3) return '🔔'
  return '📅'
}

const getNotificationIconClass = (type: 'upcoming' | 'overdue', days: number) => {
  if (type === 'overdue') return 'icon-overdue'
  if (days === 0) return 'icon-today'
  if (days <= 3) return 'icon-urgent'
  return 'icon-upcoming'
}

const getNotificationTitle = (type: 'upcoming' | 'overdue', days: number) => {
  if (type === 'overdue') {
    return `Pagamento Atrasado há ${Math.abs(days)} dia${Math.abs(days) > 1 ? 's' : ''}`
  }
  
  if (days === 0) {
    return 'Pagamento Vence Hoje'
  } else if (days === 1) {
    return 'Pagamento Vence Amanhã'
  } else {
    return `Pagamento Vence em ${days} dias`
  }
}

const handleMarkAsPaid = (notification: NotificationItem) => {
  if (confirm(`Confirmar o recebimento da parcela ${notification.installment.number} no valor de ${formatCurrency(notification.installment.value)}?`)) {
    // In real app, this would update the installment status via API
    console.log('Marking as paid:', notification)
    alert('Pagamento confirmado com sucesso!')
    
    // Remove notification from list
    const index = notifications.value.findIndex(n => n.installment.id === notification.installment.id)
    if (index > -1) {
      notifications.value.splice(index, 1)
    }
  }
}

// Load notifications when modal opens
watch(() => props.visible, (newVisible) => {
  if (newVisible) {
    loadNotifications()
  }
})
</script>

<style scoped>
.modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0, 0, 0, 0.5);
  display: flex;
  align-items: flex-end;
  justify-content: center;
  z-index: 1000;
}

.modal-content {
  background: white;
  border-radius: 1rem 1rem 0 0;
  width: 100%;
  max-width: 100%;
  max-height: 90vh;
  overflow: hidden;
  box-shadow: 0 -10px 25px rgba(0, 0, 0, 0.1);
}

.modal-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 1.5rem;
  border-bottom: 1px solid var(--gray-200);
}

.modal-title {
  font-size: 1.25rem;
  font-weight: 800;
  color: var(--gray-800);
}

.close-button {
  background: none;
  border: none;
  font-size: 1.5rem;
  color: var(--gray-600);
  cursor: pointer;
  padding: 0.25rem;
}

.modal-body {
  padding: 1rem;
  max-height: 70vh;
  overflow-y: auto;
}

.loading-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 2rem;
}

.loading-spinner {
  width: 2rem;
  height: 2rem;
  border: 2px solid var(--gray-200);
  border-top: 2px solid var(--primary);
  border-radius: 50%;
  animation: spin 1s linear infinite;
}

.loading-text {
  margin-top: 1rem;
  color: var(--gray-600);
}

.empty-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 2rem;
  text-align: center;
}

.empty-icon {
  font-size: 3rem;
  margin-bottom: 1rem;
}

.empty-title {
  font-size: 1.125rem;
  font-weight: 600;
  color: var(--gray-800);
  margin-bottom: 0.5rem;
}

.empty-subtitle {
  color: var(--gray-600);
}

.notifications-list {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.notification-card {
  background: var(--gray-50);
  border-radius: 0.75rem;
  padding: 1rem;
  border: 1px solid var(--gray-200);
}

.notification-header {
  display: flex;
  align-items: flex-start;
  margin-bottom: 1rem;
}

.notification-icon {
  font-size: 1.5rem;
  margin-right: 1rem;
  margin-top: 0.25rem;
}

.notification-content {
  flex: 1;
  margin-right: 1rem;
}

.notification-title {
  font-size: 1rem;
  font-weight: 700;
  color: var(--gray-800);
  margin-bottom: 0.25rem;
}

.customer-name {
  font-size: 0.875rem;
  font-weight: 600;
  color: var(--gray-700);
  margin-bottom: 0.25rem;
}

.product-name, .installment-info {
  font-size: 0.8125rem;
  color: var(--gray-600);
  margin-bottom: 0.25rem;
}

.notification-values {
  text-align: right;
}

.amount {
  font-size: 1rem;
  font-weight: 800;
  color: var(--gray-800);
  margin-bottom: 0.25rem;
}

.due-date {
  font-size: 0.75rem;
  color: var(--gray-600);
}

.notification-actions {
  display: flex;
  justify-content: flex-end;
  padding-top: 0.5rem;
  border-top: 1px solid var(--gray-200);
}

.pay-button {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.5rem 1rem;
  background: var(--success);
  color: white;
  border: none;
  border-radius: 0.5rem;
  font-size: 0.875rem;
  font-weight: 600;
  cursor: pointer;
  transition: opacity 0.2s ease;
}

.pay-button:hover {
  opacity: 0.9;
}

.pay-icon {
  font-size: 1rem;
}

@keyframes spin {
  from {
    transform: rotate(0deg);
  }
  to {
    transform: rotate(360deg);
  }
}
</style>

// src/components/NotificationCenter.tsx
import React, { useEffect, useState } from 'react';
import { View, Text, StyleSheet, TouchableOpacity, Modal, ScrollView, Alert } from 'react-native';
import { MaterialIcons } from '@expo/vector-icons';
import theme from '@theme';
import { Sale, MultiSale, Installment } from '@types';
import { formatCurrencyBRL, formatDateBR } from '@utils/format';
import { NotificationService } from '@services/NotificationService';
import { LocalData } from '@api/local';
import Card from './Card';

type NotificationItem = {
  sale: Sale | MultiSale;
  installment: Installment;
  daysUntilDue: number;
  daysOverdue?: number;
  type: 'upcoming' | 'overdue';
};

type Props = {
  visible: boolean;
  onClose: () => void;
};

export default function NotificationCenter({ visible, onClose }: Props) {
  const [notifications, setNotifications] = useState<NotificationItem[]>([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (visible) {
      loadNotifications();
    }
  }, [visible]);

  const loadNotifications = async () => {
    setLoading(true);
    try {
      const { upcoming, overdue } = await NotificationService.checkUpcomingPayments();
      
      const notificationItems: NotificationItem[] = [
        ...upcoming.map(item => ({
          ...item,
          type: 'upcoming' as const
        })),
        ...overdue.map(item => ({
          ...item,
          type: 'overdue' as const,
          daysOverdue: item.daysOverdue
        }))
      ];
      
      setNotifications(notificationItems);
    } catch (error) {
      console.error('Error loading notifications:', error);
    } finally {
      setLoading(false);
    }
  };

  const getNotificationIcon = (type: 'upcoming' | 'overdue', days: number): keyof typeof MaterialIcons.glyphMap => {
    if (type === 'overdue') return 'warning';
    if (days === 0) return 'schedule';
    if (days <= 3) return 'notification-important';
    return 'event';
  };

  const getNotificationColor = (type: 'upcoming' | 'overdue', days: number) => {
    if (type === 'overdue') {
      return theme.colors.danger;
    }
    
    if (days === 0) {
      return theme.colors.warning;
    } else if (days <= 3) {
      return theme.colors.warning;
    } else {
      return theme.colors.primary;
    }
  };

  const getNotificationTitle = (type: 'upcoming' | 'overdue', days: number) => {
    if (type === 'overdue') {
      return `Pagamento Atrasado há ${days} dia${days > 1 ? 's' : ''}`;
    }
    
    if (days === 0) {
      return 'Pagamento Vence Hoje';
    } else if (days === 1) {
      return 'Pagamento Vence Amanhã';
    } else {
      return `Pagamento Vence em ${days} dias`;
    }
  };

  const handleMarkAsPaid = async (notification: NotificationItem) => {
    Alert.alert(
      'Confirmar Pagamento',
      `Confirmar o recebimento da parcela ${notification.installment.number} no valor de ${formatCurrencyBRL(notification.installment.value)}?`,
      [
        { text: 'Cancelar', style: 'cancel' },
        {
          text: 'Confirmar',
          onPress: async () => {
            try {
              // Update the installment status
              const sales = await LocalData.salesHistory();
              const saleIndex = sales.findIndex(s => s.dateISO === notification.sale.dateISO);
              
              if (saleIndex >= 0 && sales[saleIndex].installments) {
                const installmentIndex = sales[saleIndex].installments!.findIndex(
                  inst => inst.id === notification.installment.id
                );
                
                if (installmentIndex >= 0) {
                  sales[saleIndex].installments![installmentIndex].status = 'paid';
                  sales[saleIndex].installments![installmentIndex].paidDate = new Date().toISOString();
                  
                  // Update the sale status
                  const allPaid = sales[saleIndex].installments!.every(inst => inst.status === 'paid');
                  sales[saleIndex].status = allPaid ? 'paid' : 'partial';
                  
                  // Save back to storage
                  await LocalData.seedSalesIfEmpty(sales);
                  // Push installment status update to Sheets (append a new row reflecting paidDate)
                  try {
                    await fetch('/.netlify/functions/sheets?table=installments', {
                      method: 'POST',
                      headers: { 'Content-Type': 'application/json' },
                      body: JSON.stringify({
                        mode: 'append',
                        rows: [{
                          saleDateISO: sales[saleIndex].dateISO,
                          installmentId: sales[saleIndex].installments![installmentIndex].id,
                          number: sales[saleIndex].installments![installmentIndex].number,
                          value: sales[saleIndex].installments![installmentIndex].value,
                          dueDate: sales[saleIndex].installments![installmentIndex].dueDate,
                          status: sales[saleIndex].installments![installmentIndex].status,
                          paidDate: sales[saleIndex].installments![installmentIndex].paidDate || ''
                        }]
                      })
                    });
                  } catch {}
                  await loadNotifications();
                  
                  Alert.alert('Sucesso', 'Pagamento confirmado com sucesso!');
                }
              }
            } catch (error) {
              Alert.alert('Erro', 'Falha ao confirmar pagamento');
            }
          }
        }
      ]
    );
  };

  const renderNotificationItem = (notification: NotificationItem, index: number) => {
    const customerName = notification.sale.customerName || 'Cliente não informado';
    const productName = 'items' in notification.sale ? 
      notification.sale.items.map(item => item.product).join(', ') : 
      notification.sale.product;
    
    const icon = getNotificationIcon(notification.type, notification.daysUntilDue);
    const color = getNotificationColor(notification.type, notification.daysUntilDue);
    const title = getNotificationTitle(notification.type, notification.daysUntilDue);
    
    return (
      <Card key={index} shadow="sm" style={styles.notificationCard}>
        <View style={styles.notificationHeader}>
          <View style={styles.notificationIcon}>
            <MaterialIcons name={icon} size={24} color={color} />
          </View>
          <View style={styles.notificationContent}>
            <Text style={styles.notificationTitle}>{title}</Text>
            <Text style={styles.customerName}>{customerName}</Text>
            <Text style={styles.productName}>{productName}</Text>
            <Text style={styles.installmentInfo}>
              Parcela {notification.installment.number} de {notification.sale.installments?.length}
            </Text>
          </View>
          <View style={styles.notificationValues}>
            <Text style={styles.amount}>{formatCurrencyBRL(notification.installment.value)}</Text>
            <Text style={styles.dueDate}>
              {formatDateBR(notification.installment.dueDate)}
            </Text>
          </View>
        </View>
        
        <View style={styles.notificationActions}>
          <TouchableOpacity
            style={[styles.actionButton, styles.payButton]}
            onPress={() => handleMarkAsPaid(notification)}
          >
            <MaterialIcons name="check" size={16} color="white" />
            <Text style={styles.actionButtonText}>Marcar como Pago</Text>
          </TouchableOpacity>
        </View>
      </Card>
    );
  };

  return (
    <Modal
      animationType="slide"
      transparent={true}
      visible={visible}
      onRequestClose={onClose}
    >
      <View style={styles.overlay}>
        <View style={styles.container}>
          <View style={styles.header}>
            <Text style={styles.headerTitle}>Notificações</Text>
            <TouchableOpacity onPress={onClose} style={styles.closeButton}>
              <MaterialIcons name="close" size={24} color={theme.colors.text} />
            </TouchableOpacity>
          </View>
          
          <ScrollView style={styles.content} showsVerticalScrollIndicator={false}>
            {loading ? (
              <View style={styles.loadingContainer}>
                <Text style={styles.loadingText}>Carregando notificações...</Text>
              </View>
            ) : notifications.length === 0 ? (
              <View style={styles.emptyContainer}>
                <MaterialIcons name="check-circle-outline" size={48} color={theme.colors.success} />
                <Text style={styles.emptyTitle}>Nenhuma notificação</Text>
                <Text style={styles.emptySubtitle}>Todos os pagamentos estão em dia!</Text>
              </View>
            ) : (
              notifications.map((notification, index) => renderNotificationItem(notification, index))
            )}
          </ScrollView>
        </View>
      </View>
    </Modal>
  );
}

const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end'
  },
  container: {
    backgroundColor: theme.colors.card,
    borderTopLeftRadius: theme.radius.xl,
    borderTopRightRadius: theme.radius.xl,
    maxHeight: '80%',
    ...theme.shadows.lg
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: theme.spacing(3),
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: theme.colors.text
  },
  closeButton: {
    padding: theme.spacing(0.5)
  },
  content: {
    flex: 1,
    padding: theme.spacing(2)
  },
  loadingContainer: {
    alignItems: 'center',
    padding: theme.spacing(4)
  },
  loadingText: {
    fontSize: 16,
    color: theme.colors.muted
  },
  emptyContainer: {
    alignItems: 'center',
    padding: theme.spacing(4)
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: theme.colors.text,
    marginTop: theme.spacing(2)
  },
  emptySubtitle: {
    fontSize: 14,
    color: theme.colors.muted,
    marginTop: theme.spacing(1),
    textAlign: 'center'
  },
  notificationCard: {
    marginBottom: theme.spacing(2),
    padding: theme.spacing(2)
  },
  notificationHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: theme.spacing(2)
  },
  notificationIcon: {
    marginRight: theme.spacing(2),
    marginTop: theme.spacing(0.5)
  },
  notificationContent: {
    flex: 1,
    marginRight: theme.spacing(2)
  },
  notificationTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: theme.colors.text,
    marginBottom: theme.spacing(0.5)
  },
  customerName: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.colors.text,
    marginBottom: theme.spacing(0.5)
  },
  productName: {
    fontSize: 13,
    color: theme.colors.muted,
    marginBottom: theme.spacing(0.5)
  },
  installmentInfo: {
    fontSize: 12,
    color: theme.colors.muted
  },
  notificationValues: {
    alignItems: 'flex-end'
  },
  amount: {
    fontSize: 16,
    fontWeight: '800',
    color: theme.colors.text,
    marginBottom: theme.spacing(0.5)
  },
  dueDate: {
    fontSize: 12,
    color: theme.colors.muted
  },
  notificationActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    paddingTop: theme.spacing(1),
    borderTopWidth: 1,
    borderTopColor: theme.colors.border
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: theme.spacing(2),
    paddingVertical: theme.spacing(1),
    borderRadius: theme.radius.sm,
    gap: theme.spacing(0.5)
  },
  payButton: {
    backgroundColor: theme.colors.success
  },
  actionButtonText: {
    fontSize: 12,
    color: 'white',
    fontWeight: '600'
  }
});
