// src/components/SaleDetailsModal.tsx
import React from 'react';
import { View, Text, StyleSheet, Modal, Pressable, TouchableOpacity, ScrollView, Linking, Alert } from 'react-native';
import { MaterialIcons } from '@expo/vector-icons';
import theme from '@theme';
import { Sale, MultiSale, Installment } from '@types';
import { formatCurrencyBRL, formatDateBR } from '@utils/format';
import Card from './Card';

type Props = {
  sale: Sale | MultiSale;
  visible: boolean;
  onClose: () => void;
};

export default function SaleDetailsModal({ sale, visible, onClose }: Props) {
  const isMultiSale = 'items' in sale;
  const hasInstallments = sale.installments && sale.installments.length > 0;

  const handleWhatsAppReceipt = () => {
    if (!sale.customerPhone) {
      Alert.alert('Erro', 'Telefone do cliente não informado');
      return;
    }

    const message = `📋 *Comprovante de Venda*\n\n` +
      `🛍️ *Produto(s):*\n` +
      (isMultiSale 
        ? sale.items.map(item => `• ${item.product} (${item.quantity}x) - ${formatCurrencyBRL(item.totalValue)}`).join('\n')
        : `• ${sale.product} (${sale.quantity}x) - ${formatCurrencyBRL(sale.totalValue)}`
      ) +
      `\n\n💰 *Total: ${formatCurrencyBRL(sale.totalValue)}*\n` +
      `📅 *Data: ${formatDateBR(sale.dateISO)}*\n` +
      `💳 *Pagamento: ${sale.paymentMethod || 'Não informado'}*\n\n` +
      `Obrigado pela preferência! 🎉`;

    const whatsappUrl = `whatsapp://send?phone=${sale.customerPhone}&text=${encodeURIComponent(message)}`;
    
    Linking.openURL(whatsappUrl).catch(() => {
      Alert.alert('Erro', 'Não foi possível abrir o WhatsApp');
    });
  };

  const getStatusColor = (status?: string) => {
    switch (status) {
      case 'paid': return theme.colors.success;
      case 'pending': return theme.colors.warning;
      case 'partial': return theme.colors.primary;
      default: return theme.colors.muted;
    }
  };

  const getStatusText = (status?: string) => {
    switch (status) {
      case 'paid': return 'Pago';
      case 'pending': return 'Pendente';
      case 'partial': return 'Parcial';
      default: return 'Não informado';
    }
  };

  return (
    <Modal
      animationType="slide"
      transparent={true}
      visible={visible}
      onRequestClose={onClose}
    >
      <View style={styles.overlay}>
        <Pressable style={styles.backdrop} onPress={onClose} />
        <View style={styles.modal}>
          <View style={styles.header}>
            <Text style={styles.title}>Detalhes da Venda</Text>
            <TouchableOpacity onPress={onClose} style={styles.closeButton}>
              <MaterialIcons name="close" size={24} color={theme.colors.text} />
            </TouchableOpacity>
          </View>

          <ScrollView style={styles.content} showsVerticalScrollIndicator={false}>
            {/* Informações do Cliente */}
            {sale.customerName && (
              <Card shadow="sm" style={styles.section}>
                <Text style={styles.sectionTitle}>Cliente</Text>
                <View style={styles.infoRow}>
                  <Text style={styles.label}>Nome:</Text>
                  <Text style={styles.value}>{sale.customerName}</Text>
                </View>
                {sale.customerPhone && (
                  <View style={styles.infoRow}>
                    <Text style={styles.label}>Telefone:</Text>
                    <Text style={styles.value}>{sale.customerPhone}</Text>
                  </View>
                )}
              </Card>
            )}

            {/* Produtos */}
            <Card shadow="sm" style={styles.section}>
              <Text style={styles.sectionTitle}>Produtos</Text>
              {isMultiSale ? (
                sale.items.map((item, index) => (
                  <View key={index} style={styles.productItem}>
                    <View style={styles.productInfo}>
                      <Text style={styles.productName}>{item.product}</Text>
                      <Text style={styles.productQuantity}>Qtd: {item.quantity}</Text>
                    </View>
                    <View style={styles.productValues}>
                      <Text style={styles.productPrice}>{formatCurrencyBRL(item.unitPrice)}</Text>
                      <Text style={styles.productTotal}>{formatCurrencyBRL(item.totalValue)}</Text>
                    </View>
                  </View>
                ))
              ) : (
                <View style={styles.productItem}>
                  <View style={styles.productInfo}>
                    <Text style={styles.productName}>{sale.product}</Text>
                    <Text style={styles.productQuantity}>Qtd: {sale.quantity}</Text>
                  </View>
                  <View style={styles.productValues}>
                    <Text style={styles.productPrice}>{formatCurrencyBRL(sale.totalValue / sale.quantity)}</Text>
                    <Text style={styles.productTotal}>{formatCurrencyBRL(sale.totalValue)}</Text>
                  </View>
                </View>
              )}
            </Card>

            {/* Resumo Financeiro */}
            <Card shadow="sm" style={styles.section}>
              <Text style={styles.sectionTitle}>Resumo Financeiro</Text>
              <View style={styles.infoRow}>
                <Text style={styles.label}>Total da Venda:</Text>
                <Text style={[styles.value, { color: theme.colors.primary, fontWeight: '700' }]}>
                  {formatCurrencyBRL(sale.totalValue)}
                </Text>
              </View>
              <View style={styles.infoRow}>
                <Text style={styles.label}>Custo Total:</Text>
                <Text style={styles.value}>
                  {formatCurrencyBRL(isMultiSale ? sale.totalCost : sale.totalCost)}
                </Text>
              </View>
              <View style={styles.infoRow}>
                <Text style={styles.label}>Lucro:</Text>
                <Text style={[styles.value, { color: theme.colors.success, fontWeight: '700' }]}>
                  {formatCurrencyBRL(isMultiSale ? sale.totalProfit : sale.profit)}
                </Text>
              </View>
              <View style={styles.infoRow}>
                <Text style={styles.label}>Status:</Text>
                <Text style={[styles.value, { color: getStatusColor(sale.status) }]}>
                  {getStatusText(sale.status)}
                </Text>
              </View>
            </Card>

            {/* Parcelas */}
            {hasInstallments && (
              <Card shadow="sm" style={styles.section}>
                <Text style={styles.sectionTitle}>Parcelas</Text>
                {sale.installments!.map((installment, index) => (
                  <View key={index} style={styles.installmentItem}>
                    <View style={styles.installmentInfo}>
                      <Text style={styles.installmentNumber}>Parcela {installment.number}</Text>
                      <Text style={styles.installmentDate}>
                        Vencimento: {formatDateBR(installment.dueDate)}
                      </Text>
                      {installment.paidDate && (
                        <Text style={styles.installmentPaid}>
                          Pago em: {formatDateBR(installment.paidDate)}
                        </Text>
                      )}
                    </View>
                    <View style={styles.installmentValues}>
                      <Text style={styles.installmentValue}>
                        {formatCurrencyBRL(installment.value)}
                      </Text>
                      <View style={[styles.statusBadge, { backgroundColor: getStatusColor(installment.status) }]}>
                        <Text style={styles.statusText}>
                          {installment.status === 'paid' ? 'Pago' : 
                           installment.status === 'overdue' ? 'Vencido' : 'Pendente'}
                        </Text>
                      </View>
                    </View>
                  </View>
                ))}
              </Card>
            )}

            {/* Informações da Venda */}
            <Card shadow="sm" style={styles.section}>
              <Text style={styles.sectionTitle}>Informações da Venda</Text>
              <View style={styles.infoRow}>
                <Text style={styles.label}>Data:</Text>
                <Text style={styles.value}>{formatDateBR(sale.dateISO)}</Text>
              </View>
              <View style={styles.infoRow}>
                <Text style={styles.label}>Forma de Pagamento:</Text>
                <Text style={styles.value}>{sale.paymentMethod || 'Não informado'}</Text>
              </View>
            </Card>
          </ScrollView>

          {/* Botões de Ação */}
          <View style={styles.actions}>
            {sale.customerPhone && (
              <TouchableOpacity style={styles.whatsappButton} onPress={handleWhatsAppReceipt}>
                <MaterialIcons name="chat" size={20} color="white" />
                <Text style={styles.whatsappText}>Enviar Comprovante</Text>
              </TouchableOpacity>
            )}
            <TouchableOpacity style={styles.closeActionButton} onPress={onClose}>
              <Text style={styles.closeActionText}>Fechar</Text>
            </TouchableOpacity>
          </View>
        </View>
      </View>
    </Modal>
  );
}

const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end'
  },
  backdrop: {
    flex: 1
  },
  modal: {
    backgroundColor: theme.colors.card,
    borderTopLeftRadius: theme.radius.xl,
    borderTopRightRadius: theme.radius.xl,
    maxHeight: '90%',
    ...theme.shadows.lg
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: theme.spacing(3),
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border
  },
  title: {
    fontSize: 20,
    fontWeight: '800',
    color: theme.colors.text
  },
  closeButton: {
    padding: theme.spacing(0.5)
  },
  content: {
    padding: theme.spacing(3)
  },
  section: {
    marginBottom: theme.spacing(3)
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: theme.colors.text,
    marginBottom: theme.spacing(2)
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: theme.spacing(1)
  },
  label: {
    fontSize: 14,
    color: theme.colors.muted
  },
  value: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.colors.text
  },
  productItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: theme.spacing(1.5),
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border
  },
  productInfo: {
    flex: 1
  },
  productName: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.colors.text
  },
  productQuantity: {
    fontSize: 12,
    color: theme.colors.muted,
    marginTop: theme.spacing(0.5)
  },
  productValues: {
    alignItems: 'flex-end'
  },
  productPrice: {
    fontSize: 14,
    color: theme.colors.muted
  },
  productTotal: {
    fontSize: 16,
    fontWeight: '700',
    color: theme.colors.primary,
    marginTop: theme.spacing(0.5)
  },
  installmentItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: theme.spacing(1.5),
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border
  },
  installmentInfo: {
    flex: 1
  },
  installmentNumber: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.colors.text
  },
  installmentDate: {
    fontSize: 12,
    color: theme.colors.muted,
    marginTop: theme.spacing(0.5)
  },
  installmentPaid: {
    fontSize: 12,
    color: theme.colors.success,
    marginTop: theme.spacing(0.5)
  },
  installmentValues: {
    alignItems: 'flex-end'
  },
  installmentValue: {
    fontSize: 16,
    fontWeight: '700',
    color: theme.colors.text
  },
  statusBadge: {
    paddingHorizontal: theme.spacing(1),
    paddingVertical: theme.spacing(0.5),
    borderRadius: theme.radius.sm,
    marginTop: theme.spacing(0.5)
  },
  statusText: {
    fontSize: 10,
    fontWeight: '600',
    color: 'white'
  },
  actions: {
    flexDirection: 'row',
    padding: theme.spacing(3),
    gap: theme.spacing(2),
    borderTopWidth: 1,
    borderTopColor: theme.colors.border
  },
  whatsappButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#25D366',
    paddingVertical: theme.spacing(2),
    borderRadius: theme.radius.md,
    gap: theme.spacing(1)
  },
  whatsappText: {
    color: 'white',
    fontWeight: '700',
    fontSize: 16
  },
  closeActionButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.surface,
    paddingVertical: theme.spacing(2),
    borderRadius: theme.radius.md,
    borderWidth: 1,
    borderColor: theme.colors.border
  },
  closeActionText: {
    color: theme.colors.text,
    fontWeight: '600',
    fontSize: 16
  }
});

// web/src/components/SaleDetailsModal.vue
<template>
  <div v-if="visible" class="modal-overlay" @click="handleOverlayClick">
    <div class="modal-content" @click.stop>
      <div class="modal-header">
        <h2 class="modal-title">Detalhes da Venda</h2>
        <button class="close-button" @click="onClose">×</button>
      </div>

      <div class="modal-body">
        <!-- Informações do Cliente -->
        <div v-if="sale.customerName" class="section">
          <h3 class="section-title">Cliente</h3>
          <div class="info-row">
            <span class="label">Nome:</span>
            <span class="value">{{ sale.customerName }}</span>
          </div>
          <div v-if="sale.customerPhone" class="info-row">
            <span class="label">Telefone:</span>
            <span class="value">{{ sale.customerPhone }}</span>
          </div>
        </div>

        <!-- Produtos -->
        <div class="section">
          <h3 class="section-title">Produtos</h3>
          <div v-if="isMultiSale">
            <div v-for="(item, index) in sale.items" :key="index" class="product-item">
              <div class="product-info">
                <div class="product-name">{{ item.product }}</div>
                <div class="product-quantity">Qtd: {{ item.quantity }}</div>
              </div>
              <div class="product-values">
                <div class="product-price">{{ formatCurrency(item.unitPrice) }}</div>
                <div class="product-total">{{ formatCurrency(item.totalValue) }}</div>
              </div>
            </div>
          </div>
          <div v-else class="product-item">
            <div class="product-info">
              <div class="product-name">{{ sale.product }}</div>
              <div class="product-quantity">Qtd: {{ sale.quantity }}</div>
            </div>
            <div class="product-values">
              <div class="product-price">{{ formatCurrency(sale.totalValue / sale.quantity) }}</div>
              <div class="product-total">{{ formatCurrency(sale.totalValue) }}</div>
            </div>
          </div>
        </div>

        <!-- Resumo Financeiro -->
        <div class="section">
          <h3 class="section-title">Resumo Financeiro</h3>
          <div class="info-row">
            <span class="label">Total da Venda:</span>
            <span class="value total-value">{{ formatCurrency(sale.totalValue) }}</span>
          </div>
          <div class="info-row">
            <span class="label">Custo Total:</span>
            <span class="value">{{ formatCurrency(sale.totalCost) }}</span>
          </div>
          <div class="info-row">
            <span class="label">Lucro:</span>
            <span class="value profit-value">{{ formatCurrency(sale.profit) }}</span>
          </div>
          <div class="info-row">
            <span class="label">Status:</span>
            <span class="value" :class="getStatusClass(sale.status)">{{ getStatusText(sale.status) }}</span>
          </div>
        </div>

        <!-- Parcelas -->
        <div v-if="hasInstallments" class="section">
          <h3 class="section-title">Parcelas</h3>
          <div v-for="(installment, index) in sale.installments" :key="index" class="installment-item">
            <div class="installment-info">
              <div class="installment-number">Parcela {{ installment.number }}</div>
              <div class="installment-date">Vencimento: {{ formatDate(installment.dueDate) }}</div>
              <div v-if="installment.paidDate" class="installment-paid">
                Pago em: {{ formatDate(installment.paidDate) }}
              </div>
            </div>
            <div class="installment-values">
              <div class="installment-value">{{ formatCurrency(installment.value) }}</div>
              <div class="status-badge" :class="getStatusClass(installment.status)">
                {{ getInstallmentStatusText(installment.status) }}
              </div>
            </div>
          </div>
        </div>

        <!-- Informações da Venda -->
        <div class="section">
          <h3 class="section-title">Informações da Venda</h3>
          <div class="info-row">
            <span class="label">Data:</span>
            <span class="value">{{ formatDate(sale.dateISO) }}</span>
          </div>
          <div class="info-row">
            <span class="label">Forma de Pagamento:</span>
            <span class="value">{{ sale.paymentMethod || 'Não informado' }}</span>
          </div>
        </div>
      </div>

      <!-- Botões de Ação -->
      <div class="modal-actions">
        <button v-if="sale.customerPhone" class="whatsapp-button" @click="handleWhatsAppReceipt">
          <span class="whatsapp-icon">💬</span>
          Enviar Comprovante
        </button>
        <button class="close-action-button" @click="onClose">
          Fechar
        </button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { Sale, MultiSale } from '../services/api'

interface Props {
  sale: Sale | MultiSale
  visible: boolean
}

const props = defineProps<Props>()
const emit = defineEmits<{
  close: []
}>()

const isMultiSale = computed(() => 'items' in props.sale)
const hasInstallments = computed(() => props.sale.installments && props.sale.installments.length > 0)

const formatCurrency = (value: number) => {
  return new Intl.NumberFormat('pt-BR', {
    style: 'currency',
    currency: 'BRL'
  }).format(value)
}

const formatDate = (dateString: string) => {
  return new Date(dateString).toLocaleDateString('pt-BR', {
    day: '2-digit',
    month: '2-digit',
    year: 'numeric'
  })
}

const getStatusClass = (status?: string) => {
  switch (status) {
    case 'paid': return 'status-paid'
    case 'pending': return 'status-pending'
    case 'partial': return 'status-partial'
    case 'overdue': return 'status-overdue'
    default: return 'status-unknown'
  }
}

const getStatusText = (status?: string) => {
  switch (status) {
    case 'paid': return 'Pago'
    case 'pending': return 'Pendente'
    case 'partial': return 'Parcial'
    case 'overdue': return 'Vencido'
    default: return 'Não informado'
  }
}

const getInstallmentStatusText = (status?: string) => {
  switch (status) {
    case 'paid': return 'Pago'
    case 'pending': return 'Pendente'
    case 'overdue': return 'Vencido'
    default: return 'Pendente'
  }
}

const handleOverlayClick = () => {
  emit('close')
}

const onClose = () => {
  emit('close')
}

const handleWhatsAppReceipt = () => {
  if (!props.sale.customerPhone) {
    alert('Telefone do cliente não informado')
    return
  }

  const message = `📋 *Comprovante de Venda*\n\n` +
    `🛍️ *Produto(s):*\n` +
    (isMultiSale.value 
      ? props.sale.items.map(item => `• ${item.product} (${item.quantity}x) - ${formatCurrency(item.totalValue)}`).join('\n')
      : `• ${props.sale.product} (${props.sale.quantity}x) - ${formatCurrency(props.sale.totalValue)}`
    ) +
    `\n\n💰 *Total: ${formatCurrency(props.sale.totalValue)}*\n` +
    `📅 *Data: ${formatDate(props.sale.dateISO)}*\n` +
    `💳 *Pagamento: ${props.sale.paymentMethod || 'Não informado'}*\n\n` +
    `Obrigado pela preferência! 🎉`

  const whatsappUrl = `whatsapp://send?phone=${props.sale.customerPhone}&text=${encodeURIComponent(message)}`
  window.open(whatsappUrl, '_blank')
}
</script>

<style scoped>
.modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0, 0, 0, 0.5);
  display: flex;
  align-items: flex-end;
  justify-content: center;
  z-index: 1000;
}

.modal-content {
  background: white;
  border-radius: 1rem 1rem 0 0;
  width: 100%;
  max-width: 100%;
  max-height: 90vh;
  overflow: hidden;
  box-shadow: 0 -10px 25px rgba(0, 0, 0, 0.1);
}

.modal-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 1.5rem;
  border-bottom: 1px solid var(--gray-200);
}

.modal-title {
  font-size: 1.25rem;
  font-weight: 800;
  color: var(--gray-800);
}

.close-button {
  background: none;
  border: none;
  font-size: 1.5rem;
  color: var(--gray-600);
  cursor: pointer;
  padding: 0.25rem;
}

.modal-body {
  padding: 1.5rem;
  max-height: 60vh;
  overflow-y: auto;
}

.section {
  margin-bottom: 1.5rem;
}

.section-title {
  font-size: 1.125rem;
  font-weight: 700;
  color: var(--gray-800);
  margin-bottom: 1rem;
}

.info-row {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 0.5rem 0;
  border-bottom: 1px solid var(--gray-100);
}

.label {
  font-size: 0.875rem;
  color: var(--gray-600);
}

.value {
  font-size: 0.875rem;
  font-weight: 600;
  color: var(--gray-800);
}

.total-value {
  color: var(--primary);
  font-weight: 700;
}

.profit-value {
  color: var(--success);
  font-weight: 700;
}

.status-paid {
  color: var(--success);
}

.status-pending {
  color: var(--warning);
}

.status-partial {
  color: var(--primary);
}

.status-overdue {
  color: var(--danger);
}

.status-unknown {
  color: var(--gray-500);
}

.product-item {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 0.75rem 0;
  border-bottom: 1px solid var(--gray-100);
}

.product-info {
  flex: 1;
}

.product-name {
  font-size: 1rem;
  font-weight: 600;
  color: var(--gray-800);
}

.product-quantity {
  font-size: 0.75rem;
  color: var(--gray-500);
  margin-top: 0.25rem;
}

.product-values {
  text-align: right;
}

.product-price {
  font-size: 0.875rem;
  color: var(--gray-600);
}

.product-total {
  font-size: 1rem;
  font-weight: 700;
  color: var(--primary);
  margin-top: 0.25rem;
}

.installment-item {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 0.75rem 0;
  border-bottom: 1px solid var(--gray-100);
}

.installment-info {
  flex: 1;
}

.installment-number {
  font-size: 1rem;
  font-weight: 600;
  color: var(--gray-800);
}

.installment-date {
  font-size: 0.75rem;
  color: var(--gray-500);
  margin-top: 0.25rem;
}

.installment-paid {
  font-size: 0.75rem;
  color: var(--success);
  margin-top: 0.25rem;
}

.installment-values {
  text-align: right;
}

.installment-value {
  font-size: 1rem;
  font-weight: 700;
  color: var(--gray-800);
}

.status-badge {
  padding: 0.25rem 0.5rem;
  border-radius: 0.25rem;
  font-size: 0.625rem;
  font-weight: 600;
  color: white;
  margin-top: 0.25rem;
  display: inline-block;
}

.status-badge.status-paid {
  background-color: var(--success);
}

.status-badge.status-pending {
  background-color: var(--warning);
}

.status-badge.status-overdue {
  background-color: var(--danger);
}

.modal-actions {
  display: flex;
  padding: 1.5rem;
  gap: 0.75rem;
  border-top: 1px solid var(--gray-200);
}

.whatsapp-button {
  flex: 1;
  display: flex;
  align-items: center;
  justify-content: center;
  background: #25D366;
  color: white;
  border: none;
  border-radius: 0.5rem;
  padding: 0.75rem;
  font-weight: 700;
  font-size: 1rem;
  cursor: pointer;
  gap: 0.5rem;
}

.whatsapp-icon {
  font-size: 1.25rem;
}

.close-action-button {
  flex: 1;
  background: var(--gray-100);
  color: var(--gray-800);
  border: 1px solid var(--gray-300);
  border-radius: 0.5rem;
  padding: 0.75rem;
  font-weight: 600;
  font-size: 1rem;
  cursor: pointer;
}

@media (max-width: 768px) {
  .modal-content {
    border-radius: 0;
  }
  
  .modal-actions {
    flex-direction: column;
  }
}
</style>
